require 'tempfile'
require 'pathname'
require 'net/http'
require 'tempfile'

test_dir = Pathname.new(__FILE__).dirname
role_dir = Pathname.new(test_dir).parent.parent.parent
role_name = Pathname.new(role_dir).basename

task default: %w[ test ]

desc 'run rspec'
task :test => [ :clean, :prepare, :do_test, :ensure_clean ] do
end

desc 'clean'
task :clean => [ :clean_vagrant, :clean_roles ] do
end

desc 'destroy vagrant nodes'
task :clean_vagrant do
  sh 'vagrant destroy -f'
  sh 'rm -f *.retry'
end

desc 'prepare the test environment'
task :prepare => [ :prepare_role, :prepare_roles, :vagrant_up ] do
end

desc 'import required roles'
task :prepare_roles do
  sh "if [ -f requirements.yml ]; then ansible-galaxy install -r requirements.yml -p roles; fi"
end

desc 'clean up required roles'
task :clean_roles do
  sh "rm -rf roles/*"
end

desc 'prepare role'
task :prepare_role do
  ignore_files = %w[ vendor .kitchen .git tests spec ].map { |f| "#{role_name}/#{f}" }
  tmpfile = Tempfile.new('.tarignore')
  tmpfile.write ignore_files.join("\n")
  tmpfile.close
  sh "tar -c -X #{tmpfile.path} -C #{role_dir.parent} -f - #{role_name} | tar -x -C #{test_dir}/roles -f -"
end

desc 'vagrant up'
task :vagrant_up do
  sh 'vagrant up'
end

desc 'do clean task even if it has been executed'
task :ensure_clean do
  Rake::Task["clean"].all_prerequisite_tasks.each do |task|
    task.reenable
  end
  Rake::Task["clean"].reenable
  Rake::Task["clean"].invoke
end

desc 'Do the test'
task :do_test do
  sh 'bundle exec rspec'
end
